### ISSUE TITLE
3scale-istio-adapter container doesn't appear in the namespace istio-system

### ISSUE THREAD

**Issue by opotmans** [Maistra/istio#11]
**Describe the bug**
3scale-istio adapter is not installed in the namespace istio-system even if the option threescale is enabled in the yaml file to deploy istio control plane
the option  disablePolicyChecks is set to false in the global section
**Expected behavior**
3scale-istio-adapter container is installed in the namespace istio-system

**Steps to reproduce the bug**
oc create/apply -f "file in attachment"

**Version**
okd 3.11
maistra 0.11 -f "file in attachment"

**Installation**
oc apply -n istio-operator -f https://raw.githubusercontent.com/Maistra/istio-operator/maistra-0.11/deploy/maistra-operator.yaml 
oc create "file in attachment"

[istio-controlplane.txt](https://github.com/Maistra/istio/files/3204051/istio-controlplane.txt)

**Environment**
on premise in a virtual machine centos
**Cluster state**
N/A

Thanks in advance for your help

Olivier

**Comment by opotmans** [comment]
when I make a oc edit controlplane/basic-install i don't see the threescale option enabled is it supported by maistra 0.11? 
olivier

**Comment by rcernich** [comment]
you need to add the following to your custom resource:

```yaml
apiVersion: istio.openshift.com/v1alpha3 
kind: ControlPlane 
metadata:
  name: basic-install
spec:
  istio:
    ...
  threeScale:
    enabled: true
```
