### ISSUE TITLE
MutatingWebhookConfiguration matches system namespaces

### ISSUE THREAD

**Issue by rvansa** [Maistra/istio#16]
**Describe the bug**
In my Openshift 3.11 installation I had `sidecar-injector` and SDN/OVS pods evicted. Subsequently the SDN pod could not start up:
```
Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: dial tcp 172.30.209.68:443: connect: connection refused
```
Apparently the webhook was called for `openshift-sdn` (and other namespaces) as these lacked the ignore label required by the webhook:
```
namespaceSelector:
    matchExpressions:
    - key: istio.openshift.com/ignore-namespace
      operator: DoesNotExist
```
The sidecar injector itself could not start because it was blocked by missing SDN.

**Expected behavior**
Any webhook configuration should exclude namespaces `openshift-*`, `kube-*` and `default`. 

**Steps to reproduce the bug**
```
oc delete -n openshift-sdn `oc get po -n openshift-sdn -o name` && oc delete -n istio-system `oc get po -n istio-system -o name`
```

**Version**
Maistra 0.10.

**Installation**
Istio-operator.

**Environment**
Openshift 3.11 on RHEL 7.6
