### ISSUE TITLE
OKD 3.11 - Maistra 0.12 : Sidecar not pushing metrics to Prometheus

### ISSUE THREAD

**Issue by atoy3731** [Maistra/istio#38]
**Describe the bug**
Even after sending traffic through service/pod, no metrics appear in Kiali/Prometheus even with sidecar injected into the container without errors. No 'istio_request_*' metrics are available in Prometheus UI.

**Expected behavior**
Metrics/graphs appear in Kiali as traffic is sent through service/proxy/pod.

**Steps to reproduce the bug**
See Installation Steps

**Version**
Istio:
```
Version: 1.0.6
GitRevision: 98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2
User: root@464fc845-2bf8-11e9-b805-0a580a2c0506
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-01T13:19:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Openshift:
```
openshift v3.11.0+82a43f6-231
kubernetes v1.11.0+d4cacc0
```

**Installation**
Using https://maistra.io/docs/getting_started/install/

My Istio installation YAML:
```
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: demo-install
spec:
  istio:
    global:
      proxy:
        # constrain resources for use in smaller environments
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi

    gateways:
      istio-egressgateway:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
      istio-ingressgateway:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false

    mixer:
      policy:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false

      telemetry:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
        # constrain resources for use in smaller environments
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      # disable autoscaling for use in smaller environments
      autoscaleEnabled: false
      # increase random sampling rate for development/testing
      traceSampling: 100.0

    kiali:
      # to disable kiali
      enabled: true

      # create a secret for accessing kiali dashboard with the following credentials
      # dashboard:
      #   user: admin
      #   passphrase: admin

    # disable grafana
    grafana:
      enabled: true

    # to disable tracing (i.e. jaeger)
    tracing:
      enabled: true
      jaeger:
        # simple, all-in-one strategy
        template: all-in-one
        # production strategy, utilizing elasticsearch
        #template: production-elasticsearch
        # if required. only one instance may use agentStrategy=DaemonSet
        #agentStrategy: DaemonSet
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  # a list of projects that should be joined into the service mesh
  # for example, to add the bookinfo project
  - demo-project
```

My NGINX test deployment/service YAML:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demo-project
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: demo-project
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        version: "1.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
```

**Environment**
Cloud Vendor: AWS
OS:  CentOS Linux release 7.6.1810 (Core)

**Cluster state**
N/A

**Comment by brian-avery** [comment]
Hi @atoy3731 
Apologies. Just seeing this now. We usually track our issues on https://issues.jboss.org/secure/RapidBoard.jspa?rapidView=4586&projectKey=MAISTRA

Our images are built by default for OpenShift 4.1, which uses nftables and isn't compatible with iptables which OCP3.11 uses. On OCP 3.11 different version of proxy-init is required, which can be configured similar to the following:

```
istio:
  global:
    multitenant: true
    proxy_init:
      image: proxy-init-centos7
```
