### ISSUE TITLE
envoyfilter to remove server name 

### ISSUE THREAD

**Issue by akilada** [Maistra/istio#90]
**Bug description**

I'm trying to create an EnvoyFilter to remove the server name from ingress gateways. However, it fails with following error.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-server-name
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        config:
          server_name: "test"
```

```
Error from server: error when creating "remove-server-name.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: envoy filter: missing filters
```

I tried to use the filter `envoy.http_connection_manager` but it doesn't have the server remove option.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**How was Istio installed?**

Redhat servicemesh operator 1.0.2
