### ISSUE TITLE
Error processing component prometheus: error: no matches for kind "Route" in version "route.openshift.io/v1"

### ISSUE THREAD

**Issue by CoaxVex** [Maistra/istio#96]
**Bug description**

I have followed instructions on deploying a service mesh control plane, but it fails to create the Route object for Prometheus.
I'm seeing the following error output on the operator output:

```
{"level":"error","ts":1585644318.4681323,"logger":"controller_servicemeshcontrolplane","caller":"controlplane/reconciler.go:302","msg":"Error processing component prometheus","error":"no matches for kind \"Route\" in version \"route.openshift.io/v1\"","errorCauses":[{"error":"no matches for kind \"Route\" in version \"route.openshift.io/v1\""}],"stacktrace":"github.com/maistra/istio-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/builddir/build/BUILD/OPERATOR/src/github.com/maistra/istio-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/maistra/istio-operator/pkg/controller/servicemesh/controlplane.(*ControlPlaneReconciler).pauseReconciliation\n\t/builddir/build/BUILD/OPERATOR/src/github.com/maistra/istio-operator/pkg/controller/servicemesh/controlplane/reconciler.go:302\ngithub.com/maistra/istio-operator/pkg/controller/servicemesh/controlplane.(*ControlPlaneReconciler).Reconcile\n\t/builddir/build/BUILD/OPERATOR/src/github.com/maistra/istio-operator/pkg/controller/servicemesh/controlplane/reconciler.go:225\ngithub.com/maistra/istio-operator/pkg/controller/servicemesh/controlplane.(*ReconcileControlPlane).Reconcile\n\t/builddir/build/BUILD/OPERATOR/src/github.com/maistra/istio-operator/pkg/controller/servicemesh/controlplane/controller.go:271\ngithub.com/maistra/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/builddir/build/BUILD/OPERATOR/src/github.com/maistra/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/maistra/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/builddir/build/BUILD/OPERATOR/src/github.com/maistra/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/maistra/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/builddir/build/BUILD/OPERATOR/src/github.com/maistra/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/maistra/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/builddir/build/BUILD/OPERATOR/src/github.com/maistra/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/maistra/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/builddir/build/BUILD/OPERATOR/src/github.com/maistra/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```
Manually creating a route works fine:
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
  namespace: istio-system
  labels:
    app: prometheus
spec:
  to:
    kind: Service
    name: prometheus
  tls:
    termination: reencrypt
```
```
oc apply -f route.yml 
route.route.openshift.io/prometheus created
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
A functional service mesh control plane.

**Steps to reproduce the bug**
Follow documentation instructions for installation on OpenShift 4.3.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Red Hat OpenShift Service Mesh 1.0.10.
```
oc version
Client Version: 4.4.0-202003060720-2576e48
Server Version: 4.3.8
Kubernetes Version: v1.16.2
```

**How was Istio installed?**
Operator through Operatorhub.
Custom resource like this:
```
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: minimal-install
spec:
  istio:
    global:
      proxy:
        # constrain resources for use in smaller environments
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi

    gateways:
      istio-egressgateway:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
      istio-ingressgateway:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false

    mixer:
      policy:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false

      telemetry:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
        # constrain resources for use in smaller environments
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      # disable autoscaling for use in smaller environments
      autoscaleEnabled: false
      # increase random sampling rate for development/testing
      traceSampling: 100.0

    kiali:
      # to disable kiali
      enabled: false

      # create a secret for accessing kiali dashboard with the following credentials
      # dashboard:
      #   user: admin
      #   passphrase: admin

    # disable grafana
    grafana:
      enabled: false

    # to disable tracing (i.e. jaeger)
    tracing:
      enabled: false
      jaeger:
        tag: 1.13.1
        # simple, all-in-one strategy
        template: all-in-one
        # production strategy, utilizing elasticsearch
        #template: production-elasticsearch
        # if required. only one instance may use agentStrategy=DaemonSet
        #agentStrategy: DaemonSet
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Bare metal. (Lab environment)
OpenShift 4.3.8.
